ideologies = [
    {
        "name": "Agrarian Socialism",
        "orgs": "Russian Socialist Revolutionary Party",
        "stats": {
            "neut": 0,
            "prol": 0,
            "stat": 50,
            "econ": 50,
            "prty": 50,
            "intl": 0,
            "bols": 0,
            "lcom": 50,
            "stal": 50,
            "ussr": 0,
            "coop": 50,
            "radc": 50,
        }
    },
    {
        "name": "Anarchist Collectivism (Bakuninism)",
        "orgs": "",
        "stats": {
            "neut": 0,
            "prol": 50,
            "stat": 0,
            "econ": 50,
            "prty": 20,
            "intl": 100,
            "bols": 50,
            "lcom": 100,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 70,
        }
    },
    {
        "name": "Anarcho-Communism (Kropotkinism)",
        "orgs": "Makhnovshchina",
        "stats": {
            "neut": 0,
            "prol": 50,
            "stat": 0,
            "econ": 50,
            "prty": 10,
            "intl": 70,
            "bols": 50,
            "lcom": 100,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Insurrectionary Anarchism",
        "orgs": "",
        "stats": {
            "neut": 0,
            "prol": 0,
            "stat": 0,
            "econ": 50,
            "prty": 0,
            "intl": 50,
            "bols": 50,
            "lcom": 100,
            "stal": 50,
            "ussr": 50,
            "coop": 10,
            "radc": 100,
        }
    },
    {
        "name": "Industrial Unionism (Syndicalism)",
        "orgs": "Industrial Workers of the World",
        "stats": {
            "neut": 50,
            "prol": 70,
            "stat": 40,
            "econ": 100,
            "prty": 30,
            "intl": 70,
            "bols": 50,
            "lcom": 50,
            "stal": 60,
            "ussr": 50,
            "coop": 50,
            "radc": 40,
        }
    },
    {
        "name": "Anarcho-Syndicalism",
        "orgs": "CNT-FAI",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 0,
            "econ": 100,
            "prty": 30,
            "intl": 80,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Postcolonial Anarchism",
        "orgs": "",
        "stats": {
            "neut": 0,
            "prol": 30,
            "stat": 0,
            "econ": 50,
            "prty": 20,
            "intl": 0,
            "bols": 20,
            "lcom": 70,
            "stal": 50,
            "ussr": 50,
            "coop": 60,
            "radc": 50,
        }
    },
    {
        "name": "Marxism (Generic)",
        "orgs": "",
        "stats": {
            "neut": 50,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 80,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Leninism (Generic)",
        "orgs": "Bolshevik Party",
        "stats": {
            "neut": 50,
            "prol": 90,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 80,
            "bols": 100,
            "lcom": 50,
            "stal": 50,
            "ussr": 70,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Kautskyism (Centrist Marxism)",
        "orgs": "Social Democratic Party of Germany (Pre-WW1)",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 40,
            "econ": 20,
            "prty": 100,
            "intl": 80,
            "bols": 0,
            "lcom": 30,
            "stal": 60,
            "ussr": 20,
            "coop": 70,
            "radc": 80,
        }
    },
    {
        "name": "Neo-Kautskyism",
        "orgs": "CPGB (PCC)",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 120,
            "intl": 80,
            "bols": 50,
            "lcom": 30,
            "stal": 20,
            "ussr": 20,
            "coop": 50,
            "radc": 80,
        }
    },
    {
        "name": "Orthodox Trotskyism",
        "orgs": "International Committee of the 4th International",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 80,
            "intl": 100,
            "bols": 100,
            "lcom": 50,
            "stal": 0,
            "ussr": 60,
            "coop": 40,
            "radc": 100,
        }
    },
    {
        "name": "Entryist Trotskyism (Pabloism/Posadism)",
        "orgs": "International Secretariat of the 4th International",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 80,
            "intl": 90,
            "bols": 100,
            "lcom": 50,
            "stal": 0,
            "ussr": 80,
            "coop": 70,
            "radc": 100,
        }
    },
    {
        "name": "Third Camp Trotskyism (Schachtmanism/Cliffism)",
        "orgs": "Worker's Party/Independent Socialist League",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 80,
            "intl": 100,
            "bols": 100,
            "lcom": 50,
            "stal": 10,
            "ussr": 20,
            "coop": 40,
            "radc": 100,
        }
    },
    {
        "name": "Post-Trotskyist Anarchism (Taborites)",
        "orgs": "The Utopian",
        "stats": {
            "neut": 0,
            "prol": 80,
            "stat": 20,
            "econ": 20,
            "prty": 20,
            "intl": 100,
            "bols": 50,
            "lcom": 50,
            "stal": 10,
            "ussr": 0,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Communalism/Democratic Confederalism", //Doesn't really belong here, but no eco category so wtv
        "orgs": "Kurdistan Workers' Party",
        "stats": {
            "neut": 0,
            "prol": 10,
            "stat": 10,
            "econ": 20,
            "prty": 30,
            "intl": 30,
            "bols": 50,
            "lcom": 50,
            "stal": 30,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Marxist Humanism",
        "orgs": "Marxist Humanist Initiative",
        "stats": {
            "neut": 0,
            "prol": 80,
            "stat": 20,
            "econ": 20,
            "prty": 50,
            "intl": 100,
            "bols": 60,
            "lcom": 70,
            "stal": 10,
            "ussr": 0,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Left-Schachtmanism (Draperites)",
        "orgs": "International Socialist Organization",
        "stats": {
            "neut": 0,
            "prol": 90,
            "stat": 33,
            "econ": 20,
            "prty": 75,
            "intl": 100,
            "bols": 90,
            "lcom": 70,
            "stal": 20,
            "ussr": 10,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Trade Unionism",
        "orgs": "AFL-CIO",
        "stats": {
            "neut": 100,
            "prol": 60,
            "stat": 50,
            "econ": 100,
            "prty": 30,
            "intl": 0,
            "bols": 20,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 20,
        }
    },
    {
        "name": "Progressivism (Social Liberalism/Post-war Social Democracy)",
        "orgs": "Social Democratic Party of Germany (Post-WW2)",
        "stats": {
            "neut": 50,
            "prol": 50,
            "stat": 80,
            "econ": 20,
            "prty": 50,
            "intl": 10,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 20,
            "coop": 50,
            "radc": 20,
        }
    },
    {
        "name": "Big-Tent Democratic Socialism (Harringtonism)",
        "orgs": "Democratic Socialists of America",
        "stats": {
            "neut": 100,
            "prol": 50,
            "stat": 50,
            "econ": 30,
            "prty": 60,
            "intl": 10,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 40,
            "coop": 70,
            "radc": 50,
        }
    },
    {
        "name": "Contemporary Class-first Socialism",
        "orgs": "",
        "stats": {
            "neut": 100,
            "prol": 80,
            "stat": 50,
            "econ": 60,
            "prty": 80,
            "intl": 30,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 50,
        }
    },
    {
        "name": "Contemporary Intersectional Leftism",
        "orgs": "",
        "stats": {
            "neut": 100,
            "prol": 30,
            "stat": 50,
            "econ": 0,
            "prty": 50,
            "intl": 20,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 80,
            "radc": 40,
        }
    },
    {
        "name": "Marxism-Leninism (Stalinism)",
        "orgs": "Communist Party of the Soviet Union",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 50,
            "bols": 100,
            "lcom": 50,
            "stal": 100,
            "ussr": 100,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Anti-Revisionist Marxism-Leninism (Stalinism/Hoxhaism)",
        "orgs": "Party of Labour of Albania",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 50,
            "bols": 100,
            "lcom": 50,
            "stal": 100,
            "ussr": 30,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Titoism",
        "orgs": "League of Communists of Yugoslavia",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 30,
            "bols": 100,
            "lcom": 70,
            "stal": 100,
            "ussr": 30,
            "coop": 70,
            "radc": 60,
        }
    },
    {
        "name": "Mao Zedong Thought",
        "orgs": "Communist Party of China (Pre-Deng)",
        "stats": {
            "neut": 0,
            "prol": 50,
            "stat": 50,
            "econ": 60,
            "prty": 100,
            "intl": 0,
            "bols": 100,
            "lcom": 40,
            "stal": 100,
            "ussr": 60,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Marxism-Leninism-Maoism",
        "orgs": "Revolutionary Internationalist Movement",
        "stats": {
            "neut": 0,
            "prol": 50,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 20,
            "bols": 100,
            "lcom": 70,
            "stal": 100,
            "ussr": 50,
            "coop": 40,
            "radc": 60,
        }
    },
    {
        "name": "Deng Xiaoping Thought",
        "orgs": "Communist Party of China (Post-Mao)",
        "stats": {
            "neut": 0,
            "prol": 50,
            "stat": 60,
            "econ": 40,
            "prty": 100,
            "intl": 0,
            "bols": 100,
            "lcom": 0,
            "stal": 100,
            "ussr": 30,
            "coop": 60,
            "radc": 50,
        }
    },
    {
        "name": "Right-Communism (Bukharinism)",
        "orgs": "Russian Communist Party (Right Opposition)",
        "stats": {
            "neut": 0,
            "prol": 80,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 70,
            "bols": 100,
            "lcom": 0,
            "stal": 50,
            "ussr": 80,
            "coop": 60,
            "radc": 70,
        }
    },
    {
        "name": "Autonomist Marxism",
        "orgs": "",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 25,
            "econ": 20,
            "prty": 30,
            "intl": 100,
            "bols": 60,
            "lcom": 80,
            "stal": 50,
            "ussr": 30,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Eurocommunism",
        "orgs": "",
        "stats": {
            "neut": 30,
            "prol": 70,
            "stat": 60,
            "econ": 40,
            "prty": 70,
            "intl": 50,
            "bols": 50,
            "lcom": 40,
            "stal": 50,
            "ussr": 0,
            "coop": 80,
            "radc": 50,
        }
    },
    {
        "name": "Left-Communism (Council Communism)",
        "orgs": "Communist Workers' Party of Germany",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 30,
            "econ": 20,
            "prty": 70,
            "intl": 100,
            "bols": 80,
            "lcom": 100,
            "stal": 50,
            "ussr": 60,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Bolshevik Left Opposition",
        "orgs": "Russian Communist Party (Left Opposition)",
        "stats": {
            "neut": 0,
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 100,
            "bols": 100,
            "lcom": 80,
            "stal": 50,
            "ussr": 60,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Reformist Marxism (Bernsteinian Social Democracy)",
        "orgs": "Independent Social Democratic Party of Germany",
        "stats": {
            "neut": 0,
            "prol": 70,
            "stat": 60,
            "econ": 50,
            "prty": 100,
            "intl": 50,
            "bols": 0,
            "lcom": 0,
            "stal": 50,
            "ussr": 0,
            "coop": 80,
            "radc": 70,
        }
    },
];
