ideologies = [
    {
        "name": "Agrarian Socialism (Narodniks/Socialist Revolutionaries)",
        "stats": {
            "prol": 0,
            "stat": 50,
            "econ": 50,
            "prty": 50,
            "intl": 0,
            "bols": 0,
            "lcom": 50,
            "stal": 50,
            "ussr": 0,
            "coop": 50,
            "radc": 50,
        }
    },
    {
        "name": "Agrarian Anarchism (Makhnovshchina)",
        "stats": {
            "prol": 0,
            "stat": 0,
            "econ": 50,
            "prty": 10,
            "intl": 70,
            "bols": 10,
            "lcom": 50,
            "stal": 50,
            "ussr": 0,
            "coop": 50,
            "radc": 50,
        }
    },
    {
        "name": "Anarchist Collectivism (Bakuninism)",
        "stats": {
            "prol": 60,
            "stat": 0,
            "econ": 50,
            "prty": 20,
            "intl": 100,
            "bols": 50,
            "lcom": 100,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 70,
        }
    },
    {
        "name": "Anarcho-Communism",
        "stats": {
            "prol": 100,
            "stat": 0,
            "econ": 50,
            "prty": 0,
            "intl": 50,
            "bols": 50,
            "lcom": 100,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Industrial Unionism (Syndicalism)",
        "stats": {
            "prol": 100,
            "stat": 40,
            "econ": 100,
            "prty": 30,
            "intl": 70,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 40,
        }
    },
    {
        "name": "Anarcho-Syndicalism",
        "stats": {
            "prol": 100,
            "stat": 0,
            "econ": 100,
            "prty": 30,
            "intl": 50,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Postcolonial Anarchism",
        "stats": {
            "prol": 50,
            "stat": 0,
            "econ": 50,
            "prty": 20,
            "intl": 0,
            "bols": 20,
            "lcom": 70,
            "stal": 50,
            "ussr": 50,
            "coop": 60,
            "radc": 50,
        }
    },
    {
        "name": "Classical Marxism",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 0,
            "prty": 100,
            "intl": 90,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Classical Leninism",
        "stats": {
            "prol": 90,
            "stat": 33,
            "econ": 0,
            "prty": 100,
            "intl": 90,
            "bols": 100,
            "lcom": 50,
            "stal": 50,
            "ussr": 70,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Kautskyism (Centrist Marxism)",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 80,
            "bols": 0,
            "lcom": 30,
            "stal": 60,
            "ussr": 20,
            "coop": 70,
            "radc": 80,
        }
    },
    {
        "name": "Orthodox Trotskyism",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 0,
            "prty": 100,
            "intl": 100,
            "bols": 100,
            "lcom": 50,
            "stal": 0,
            "ussr": 60,
            "coop": 40,
            "radc": 100,
        }
    },
    {
        "name": "Entryist Trotskyism (Pabloism/Posadism)",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 0,
            "prty": 100,
            "intl": 100,
            "bols": 100,
            "lcom": 50,
            "stal": 0,
            "ussr": 80,
            "coop": 70,
            "radc": 100,
        }
    },
    {
        "name": "Third Camp Trotskyism (Schachtmanism/Cliffism)",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 100,
            "bols": 100,
            "lcom": 50,
            "stal": 0,
            "ussr": 20,
            "coop": 40,
            "radc": 100,
        }
    },
    {
        "name": "Post-Trotskyist Anarchism (Taborites)",
        "stats": {
            "prol": 100,
            "stat": 20,
            "econ": 20,
            "prty": 20,
            "intl": 100,
            "bols": 50,
            "lcom": 50,
            "stal": 20,
            "ussr": 0,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Communalism (Bookchin)",
        "stats": {
            "prol": 10,
            "stat": 10,
            "econ": 0,
            "prty": 30,
            "intl": 80,
            "bols": 50,
            "lcom": 50,
            "stal": 10,
            "ussr": 50,
            "coop": 50,
            "radc": 100,
        }
    },
    {
        "name": "Marxist Humanism",
        "stats": {
            "prol": 100,
            "stat": 20,
            "econ": 0,
            "prty": 50,
            "intl": 100,
            "bols": 60,
            "lcom": 70,
            "stal": 0,
            "ussr": 0,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Left-Schachtmanism (Draperites)",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 0,
            "prty": 75,
            "intl": 100,
            "bols": 90,
            "lcom": 70,
            "stal": 10,
            "ussr": 10,
            "coop": 30,
            "radc": 100,
        }
    },
    {
        "name": "Trade Unionism",
        "stats": {
            "prol": 80,
            "stat": 50,
            "econ": 100,
            "prty": 30,
            "intl": 0,
            "bols": 20,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 20,
        }
    },
    {
        "name": "Progressivism (Social Liberalism/Post-war Social Democracy)",
        "stats": {
            "prol": 50,
            "stat": 80,
            "econ": 20,
            "prty": 50,
            "intl": 10,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 20,
            "coop": 50,
            "radc": 20,
        }
    },
    {
        "name": "Big-Tent Democratic Socialism (Harringtonism)",
        "stats": {
            "prol": 50,
            "stat": 50,
            "econ": 30,
            "prty": 60,
            "intl": 10,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 40,
            "coop": 70,
            "radc": 50,
        }
    },
    {
        "name": "Contemporary Class-first Socialism",
        "stats": {
            "prol": 90,
            "stat": 50,
            "econ": 60,
            "prty": 80,
            "intl": 30,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 50,
            "radc": 50,
        }
    },
    {
        "name": "Contemporary Intersectional Leftism",
        "stats": {
            "prol": 30,
            "stat": 50,
            "econ": 0,
            "prty": 50,
            "intl": 20,
            "bols": 50,
            "lcom": 50,
            "stal": 50,
            "ussr": 50,
            "coop": 80,
            "radc": 40,
        }
    },
    {
        "name": "Marxism-Leninism (Stalinism)",
        "stats": {
            "prol": 80,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 50,
            "bols": 100,
            "lcom": 50,
            "stal": 100,
            "ussr": 100,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Anti-Revisionist Marxism-Leninism (Stalinism/Hoxhaism)",
        "stats": {
            "prol": 80,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 50,
            "bols": 100,
            "lcom": 50,
            "stal": 100,
            "ussr": 30,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Titoism",
        "stats": {
            "prol": 80,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 30,
            "bols": 100,
            "lcom": 70,
            "stal": 100,
            "ussr": 30,
            "coop": 70,
            "radc": 60,
        }
    },
    {
        "name": "Mao Zedong Thought",
        "stats": {
            "prol": 50,
            "stat": 50,
            "econ": 60,
            "prty": 100,
            "intl": 0,
            "bols": 100,
            "lcom": 40,
            "stal": 100,
            "ussr": 60,
            "coop": 50,
            "radc": 60,
        }
    },
    {
        "name": "Marxism-Leninism-Maoism",
        "stats": {
            "prol": 50,
            "stat": 50,
            "econ": 40,
            "prty": 100,
            "intl": 20,
            "bols": 100,
            "lcom": 70,
            "stal": 100,
            "ussr": 50,
            "coop": 40,
            "radc": 60,
        }
    },
    {
        "name": "Deng Xiaoping Thought",
        "stats": {
            "prol": 50,
            "stat": 60,
            "econ": 40,
            "prty": 100,
            "intl": 0,
            "bols": 100,
            "lcom": 0,
            "stal": 100,
            "ussr": 30,
            "coop": 60,
            "radc": 50,
        }
    },
    {
        "name": "Right-Communism (Bukharinism)",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 50,
            "bols": 100,
            "lcom": 0,
            "stal": 50,
            "ussr": 80,
            "coop": 60,
            "radc": 70,
        }
    },
    {
        "name": "Autonomist Marxism",
        "stats": {
            "prol": 100,
            "stat": 25,
            "econ": 20,
            "prty": 40,
            "intl": 100,
            "bols": 60,
            "lcom": 80,
            "stal": 50,
            "ussr": 30,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Left-Communism (Council Communism)",
        "stats": {
            "prol": 100,
            "stat": 30,
            "econ": 20,
            "prty": 70,
            "intl": 100,
            "bols": 80,
            "lcom": 80,
            "stal": 50,
            "ussr": 60,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Bolshevik Left Opposition",
        "stats": {
            "prol": 100,
            "stat": 33,
            "econ": 20,
            "prty": 100,
            "intl": 100,
            "bols": 100,
            "lcom": 70,
            "stal": 50,
            "ussr": 60,
            "coop": 0,
            "radc": 100,
        }
    },
    {
        "name": "Eurocommunism",
        "stats": {
            "prol": 100,
            "stat": 50,
            "econ": 40,
            "prty": 80,
            "intl": 50,
            "bols": 50,
            "lcom": 40,
            "stal": 40,
            "ussr": 0,
            "coop": 60,
            "radc": 50,
        }
    },
    {
        "name": "Reformist Marxism (Bernsteinian Social Democracy)",
        "stats": {
            "prol": 100,
            "stat": 60,
            "econ": 50,
            "prty": 100,
            "intl": 50,
            "bols": 0,
            "lcom": 0,
            "stal": 50,
            "ussr": 0,
            "coop": 80,
            "radc": 70,
        }
    },
];
