questions = [
    {
        "question": "The 1848 revolutions showed that the industrial proletariat was a uniquely revolutionary class against the bourgeoisie and rural classes.",
        "effect": {
            "ussr": 0,
            "prol": 10,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 10,
        }
    },
    {
        "question": "The First International was mistaken in its resolution that the working class must be involved in politics in addition to direct economic action (e.g. strikes).",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 10,
            "prty": -10,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The party socialist and anarchist factions of the First International should have reconciled their differences and stayed united.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "refo": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Paris Commune showed that the working class needs a disciplined political organization for its revolution to succeed.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": -5,
            "prty": 10,
            "intl": 0,
            "coop": 0,
            "bols": 5,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The worker's party should have followed Ferdinand Lassalle's approach of using the state to guarantee suffrage and labor protections.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": -5,
            "prty": 5,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The constituents of the First International should firstly focus on emancipation within their respective nation-states, which will in turn lead to international emancipation.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 5,
            "refo": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Socialists must demand (as in the Gotha Program) that 'the proceeds of labor belong undiminished with equal right to all members of society.'",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -10,
        }
    },
    {
        "question": "Socialists must demand (as in the Gotha Program) that the state provide universal and equal education.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -10,
        }
    },
    {
        "question": "The Possibilists were correct in their approach of focusing on winning reforms that are possible in the short term, while remaining prepared for revolution.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 5,
            "intl": 0,
            "coop": 5,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The disagreements between Possibilists and Social Democrats were primarily driven by interpersonal conflicts and stubbornness.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The Possibilists, Social Democrats, and other socialist tendencies were correct in uniting in the Second International.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "In the 19th century, Karl Kautsky was correct to try to build a party to represent the whole proletariat.",
        "effect": {
            "ussr": 0,
            "prol": 5,
            "stat": 0,
            "econ": 0,
            "prty": 10,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Second International had an excessive focus on electoral politics, and should have focused more on direct action.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": -5,
            "econ": 10,
            "prty": -5,
            "intl": 0,
            "coop": -5,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The workers of the Second International faced different difficulties in their respective countries, and should have autonomy to determine their own strategies.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Narodniks were correct to focus on local village communities as the primary emancipatory force in agrarian Russia.",
        "effect": {
            "ussr": 0,
            "prol": -10,
            "stat": -5,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The parties of the Second International should have sought to enter ministerial positions in government.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": 0,
            "prty": 5,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The French socialists should have intervened in the Dreyfus affair to ensure a just society.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": -10,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "Russian and Chinese socialists should have opposed all imperialist and capitalist intrusions into their countries.",
        "effect": {
            "ussr": 0,
            "prol": -10,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Edouard Bernstein was right in his approach to update Marxism for the new conditions of the 20th century.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The parties of the Second International should have participated in elections and parliaments where possible.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": -10,
            "prty": 10,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Pre-WW1 German Social Democratic Party was a high point in proletarian consciousness and a rightful role model for the international socialist movement.",
        "effect": {
            "ussr": 0,
            "prol": 10,
            "stat": 0,
            "econ": -5,
            "prty": 10,
            "intl": 5,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Assassinations of official figures propelled social consciousness and allowed radicals to challenge complicity in repressive governments.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": -10,
            "econ": 0,
            "prty": -10,
            "intl": 0,
            "coop": -10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Once the German Social Democrats achieved power, socialism was a matter of continuous improvement, rather than an attempt to reach any concrete goal.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": 10,
            "prty": 10,
            "intl": -5,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The Industrial Workers of the World should have abstained from working with any political parties.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": -5,
            "econ": 5,
            "prty": -10,
            "intl": 0,
            "coop": -10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "It was necessary for Lenin to split the Russian Social Democratic Party to ensure the later success of the October Revolution.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 5,
            "intl": 0,
            "coop": -5,
            "bols": 5,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Pre-WW1 Germany had relatively advanced social reforms, which needed to be defended from the reactionary Russian Empire.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 5,
            "bols": -5,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "At its root, the Second International failed to prevent WW1 due to reified consciousness among its members.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": -10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": -10,
            "impr": 0,
            "radc": 10,
        }
    },
    {
        "question": "Russia was not ready for a socialist revolution. Lenin's party should have waited until the conditions were right.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -5,
            "coop": 5,
            "bols": -20,
            "lcom": 0,
            "stal": 5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Lenin's party was authoritarian and fundamentally at odds with the goals of socialist organization.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": -5,
            "intl": 0,
            "coop": 0,
            "bols": -10,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "It was nonsensical to demand that workers give up power after the February Revolution. A further revolution was needed, whether that be Bolshevik or Anarchist or something else.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "Rosa Luxemburg opposed the Bolsheviks' authoritarianism and advocated for a more bottom-up approach to revolution.",
        "effect": {
            "ussr": -5,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": -10,
            "lcom": 10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Brest-Litovsk treaty conceded too much to German imperialism and should have been avoided.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 5,
            "coop": 0,
            "bols": 0,
            "lcom": 10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Bolsheviks' failures were in large part the fault of the German socialists.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 10,
            "coop": 0,
            "bols": 5,
            "lcom": -5,
            "stal": -10,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "National self-determination was a legitimate concern among the oppressed peoples of the Russian Empire, and the Bolsheviks should have respected their democratic governments.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The 1921 Kronstadt revolt was fundamentally petty-bourgeois. Its suppression was sad but necessary.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": -5,
            "bols": 5,
            "lcom": -5,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Russian peasantry should rise up against the harsh requisitions and collectivization imposed by the Bolsheviks.",
        "effect": {
            "ussr": 0,
            "prol": -10,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": -10,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Makhno's Free Territory managed to achieve the closest thing to true socialism up to that point in history.",
        "effect": {
            "ussr": 0,
            "prol": -5,
            "stat": -10,
            "econ": 0,
            "prty": -10,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 5,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "After the civil war, the Soviets should not have normalized relations with capitalist countries, but should have more aggressively spread revolution instead.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 5,
            "coop": 0,
            "bols": 0,
            "lcom": 10,
            "stal": -5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "In developed countries, bourgeois trade unions are too conservative and cannot be worked with in the struggle for socialism.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": -10,
            "bols": 0,
            "lcom": 5,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Under ideal conditions, the Bolsheviks would have introduced multiparty socialist democracy after winning the revolution.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": -5,
            "econ": 0,
            "prty": -5,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 5,
            "stal": -5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Avant-garde art, such as constructivism, was a petty-bourgeois distraction and had no place in the Soviet Union.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": -5,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The New Economic Policy was needed to recover from the harsh demands of the Russian Civil War.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": -10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Key to the Bolsheviks' success was their broad alliance with the peasant class, which should be replicated in other countries.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 5,
            "lcom": -10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The New Economic Policy was a temporary compromise with the specific conditions of Russia, and may not have been necessary in more advanced countries.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -5,
            "coop": 0,
            "bols": 0,
            "lcom": 10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Stalin's rise to power was a direct consequence of the authoritarianism of the Bolshevik revolution, even if they had good intentions.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": -5,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 5,
            "stal": 5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Trotsky was no better than Stalin, and he only criticized the Soviet Union after he was removed from power.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 10,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Stalin's policies were necessary to industrialize the Soviet Union and defend against capitalist powers.",
        "effect": {
            "ussr": 10,
            "prol": 0,
            "stat": 5,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 10,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Comintern's Third Period was a mistake and communists should have allied with more moderate socialists to defend against fascism.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": -5,
            "stal": -5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Stalin had popular support from the working class and did not merely rely on repressive means to stay in power.",
        "effect": {
            "ussr": 5,
            "prol": 0,
            "stat": 0,
            "econ": -10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Communist parties should have allied with liberal parties to defend against fascism.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": -5,
            "stal": 10,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "In highly agrarian countries like China or India, there was no way for communists to achieve power without adopting the peasantry as the main revolutionary class.",
        "effect": {
            "ussr": 0,
            "prol": -5,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -5,
            "coop": 0,
            "bols": 0,
            "lcom": -5,
            "stal": 5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Stalin's rise to power was a consequence of political opportunism broadly common to the Second International.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": -10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 5,
            "lcom": 0,
            "stal": -10,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Maintaining the United Front between Chinese Communists and Nationalists was needed to repel Japanese imperialism.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -5,
            "coop": 10,
            "bols": 0,
            "lcom": -5,
            "stal": 5,
            "impr": 10,
            "radc": 0,
        }
    },
    {
        "question": "The New Deal was a victory for the American working class.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 10,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 5,
            "impr": 0,
            "radc": -10,
        }
    },
    {
        "question": "African struggles for national liberation should always be supported as they inherently challenge the capitalist order.",
        "effect": {
            "ussr": 0,
            "prol": -5,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 5,
            "impr": 10,
            "radc": 0,
        }
    },
    {
        "question": "Even if the Soviet Union was not truly socialist, it was still a worker's state that should be defended against capitalist attacks.",
        "effect": {
            "ussr": 20,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 5,
            "radc": 0,
        }
    },
    {
        "question": "Mao's Cultural Revolution advanced the contradictions of society and brought forth new revolutionary spontaneity among the people.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": -10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 10,
            "stal": 5,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "To remain relevant in politics, the Pabloites were correct in their decision to enter mainstream Soviet-aligned parties.",
        "effect": {
            "ussr": 10,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 5,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    // Draper
    {
        "question": "Stalin had an approach of socialism from above, whereas Trotsky had an approach of socialism from below.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": -5,
            "econ": 0,
            "prty": -5,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 5,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The American worker's movement reached a high point in the mid-20th century.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 5,
            "econ": 5,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
    {
        "question": "The Prague Spring was a legitimate response to the authoritarianism of the Soviet Union and should have been supported.",
        "effect": {
            "ussr": -10,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The New Left was misguided because they introduced cultural concerns to the exclusion of economic issues.",
        "effect": {
            "ussr": 0,
            "prol": 5,
            "stat": 0,
            "econ": 10,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The European Social Democrats were correct to drop Marxism entirely and aim for mixed economic policies instead.",
        "effect": {
            "ussr": -10,
            "prol": 0,
            "stat": 20,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -10,
        }
    },
    {
        "question": "Postwar socialists tended to split over trivial matters, which was a significant factor in the decline of the overall socialist movement.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 10,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The stagnation of the working class in the First World suggests that new revolutionary subjects (e.g. racial or sexual minorities) must be considered.",
        "effect": {
            "ussr": 0,
            "prol": -10,
            "stat": 0,
            "econ": -10,
            "prty": -10,
            "intl": -10,
            "coop": 5,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Sino-Soviet split was justified as the USSR betrayed the revolution to pursue peaceful coexistence with capitalist states.",
        "effect": {
            "ussr": -10,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": -5,
            "bols": 0,
            "lcom": 5,
            "stal": 0,
            "impr": 10,
            "radc": 0,
        }
    },
    {
        "question": "African Americans form a distinct nation within the USA, and their struggle against white supremacy is revolutionary.",
        "effect": {
            "ussr": 0,
            "prol": -5,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 5,
            "impr": 10,
            "radc": 0,
        }
    },
    // Humanists & post-Trot anarchists
    {
        "question": "Max Schachtman did not go far enough in his critique of Soviet bureaucratic collectivism. The Leninist Party is suspect, or at least outdated.",
        "effect": {
            "ussr": -10,
            "prol": 0,
            "stat": -5,
            "econ": 0,
            "prty": -10,
            "intl": 0,
            "coop": 0,
            "bols": -5,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Given geopolitical realities, Deng Xiaoping was justified in introducing market reforms as a temporary measure to preserve the Chinese revolution.",
        "effect": {
            "ussr": 5,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": 0,
            "coop": 5,
            "bols": 0,
            "lcom": -10,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "The Iranian revolution must be defended against Western imperialism, even if it is led by religious fundamentalists.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 10,
            "radc": 0,
        }
    },
    {
        "question": "The Democratic Socialists of America is ineffectual in large part because it is led by members of the professional-managerial class.",
        "effect": {
            "ussr": 0,
            "prol": 0,
            "stat": 0,
            "econ": 10,
            "prty": 0,
            "intl": 0,
            "coop": -5,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": 0,
        }
    },
    {
        "question": "Now that the Soviet Union is gone, we can better focus on organizing workers at home.",
        "effect": {
            "ussr": -10,
            "prol": 0,
            "stat": 0,
            "econ": 0,
            "prty": 0,
            "intl": -10,
            "coop": 0,
            "bols": 0,
            "lcom": 0,
            "stal": 0,
            "impr": 0,
            "radc": -5,
        }
    },
];
